require "open-uri"
require "nokogiri"
require_relative "../lib/fender_guitar_catalogue/guitar.rb"
require_relative "../lib/fender_guitar_catalogue/cli.rb"
require_relative "../lib/fender_guitar_catalogue/scraper.rb"